name: Build docker image and run unit tests

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        load: true
        push: false
        tags: trainer-elliot:latest

    - name: Report Docker image size
      run: |
        IMAGE_ID=$(docker images -q trainer-elliot:latest)
        IMAGE_SIZE=$(docker image inspect $IMAGE_ID --format='{{.Size}}')
        echo "Docker image size: $IMAGE_SIZE bytes"
        echo "IMAGE_SIZE=$IMAGE_SIZE" >> $GITHUB_ENV

    - name: Copy and load .env.example file
      run: |
        cp .env.example .env

    - name: Run Docker container
      run: |
        docker-compose up -d

    - name: Run tests in docker container
      run: |
        chmod +x ./scripts/run_tests.sh
        ./scripts/run_tests.sh