name: PEP-8 Python code convention (black)

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.x
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.4.2
      
    - name: Run Black
      run: black --check .
